%% runBatchKalmanTests.m
% Batch runner for Kalman trend model across multiple tickers.
% Data for each ticker must be included in the data folder.
%
% This script compares:
%   1. Buy-and-hold
%   2. Baseline 0/1 Kalman strategy
%   3. Partial-exposure Kalman strategy

clear; clc; close all;

%% ---------------- Shared Parameters ----------------
params = struct();

% Current shared ETF baseline
params.q_jerk = 1e-7;
params.r_meas = 1e-3;

params.buyConfirmDays = 5;
params.sellConfirmDays = 8;

params.transactionCost = 0.001;

% Suppress plots and printed output during batch runs.
params.makePlots = true;
params.showStatePlots = false;   % price CI, trend CI, acceleration CI
params.printSummary = false;

% Enable partial-exposure comparison branch.
params.runPartialExposure = true;

%% ---------------- Tickers to Test ----------------
tickers = ["SPY", "QQQ", "SPYG"];

numTickers = length(tickers);

summaryRows = table();

%% ---------------- Run Batch Tests ----------------
for i = 1:numTickers

    ticker = tickers(i);
    filename = "data/" + ticker + ".csv";

    fprintf("Running %s...\n", ticker);

    [results, summary] = runKalmanTrendModel_partialExposure(filename, params); %#ok<ASGLU>

    newRow = table( ...
        ticker, ...
        summary.startDate, ...
        summary.endDate, ...
        summary.q_jerk, ...
        summary.r_meas, ...
        summary.buyConfirmDays, ...
        summary.sellConfirmDays, ...
        100*summary.buyHoldTotalReturn, ...
        100*summary.baselineTotalReturn, ...
        100*summary.exposureTotalReturn, ...
        100*summary.buyHoldMaxDrawdown, ...
        100*summary.baselineMaxDrawdown, ...
        100*summary.exposureMaxDrawdown, ...
        summary.buyHoldSharpeApprox, ...
        summary.baselineSharpeApprox, ...
        summary.exposureSharpeApprox, ...
        summary.buyHoldBuyCount, ...
        summary.baselineBuyCount, ...
        summary.exposureBuyCount, ...
        summary.buyHoldSellCount, ...
        summary.baselineSellCount, ...
        summary.exposureSellCount, ...
        summary.buyHoldTradeCount, ...
        summary.baselineTradeCount, ...
        summary.exposureTradeCount, ...
        100*summary.buyHoldTimeInMarket, ...
        100*summary.baselineTimeInMarket, ...
        100*summary.exposureTimeInMarket, ...
        100*summary.averageExposure, ...
        summary.exposureTurnoverTotal, ...
        100*summary.buyHoldExcessReturn, ...
        100*summary.baselineExcessReturn, ...
        100*summary.exposureExcessReturn, ...
        100*summary.buyHoldDrawdownImprovement, ...
        100*summary.baselineDrawdownImprovement, ...
        100*summary.exposureDrawdownImprovement, ...
        summary.buyHoldSharpeImprovement, ...
        summary.baselineSharpeImprovement, ...
        summary.exposureSharpeImprovement, ...
        'VariableNames', [ ...
        "Ticker", ...
        "StartDate", ...
        "EndDate", ...
        "q_jerk", ...
        "r_meas", ...
        "BuyConfirmDays", ...
        "SellConfirmDays", ...
        "BuyHoldReturnPct", ...
        "BaselineReturnPct", ...
        "ExposureReturnPct", ...
        "BuyHoldMaxDrawdownPct", ...
        "BaselineMaxDrawdownPct", ...
        "ExposureMaxDrawdownPct", ...
        "BuyHoldSharpe", ...
        "BaselineSharpe", ...
        "ExposureSharpe", ...
        "BuyHoldBuyCount", ...
        "BaselineBuyCount", ...
        "ExposureBuyCount", ...
        "BuyHoldSellCount", ...
        "BaselineSellCount", ...
        "ExposureSellCount", ...
        "BuyHoldTradeCount", ...
        "BaselineTradeCount", ...
        "ExposureTradeCount", ...
        "BuyHoldTimeInMarketPct", ...
        "BaselineTimeInMarketPct", ...
        "ExposureTimeInMarketPct", ...
        "ExposureAveragePct", ...
        "ExposureTurnoverTotal", ...
        "BuyHoldExcessReturnPct", ...
        "BaselineExcessReturnPct", ...
        "ExposureExcessReturnPct", ...
        "BuyHoldDrawdownImprovementPct", ...
        "BaselineDrawdownImprovementPct", ...
        "ExposureDrawdownImprovementPct", ...
        "BuyHoldSharpeImprovement", ...
        "BaselineSharpeImprovement", ...
        "ExposureSharpeImprovement"]);

    summaryRows = [summaryRows; newRow];

end

%% ---------------- Display Summary ----------------
disp(summaryRows);

%% ---------------- Save Results ----------------
if ~isfolder("results")
    mkdir("results");
end

if ~isfolder("results/batchruns")
    mkdir("results/batchruns");
end

outFile = "results/batchruns/new_batch_kalman_summary.xlsx";
writetable(summaryRows, outFile);

fprintf("\nBatch summary saved to: %s\n", outFile);
