%% runSelectedConfigBatchKalmanTests.m
% Batch runner for selected Kalman strategy configurations.
%
% Purpose:
%   Compare a selected-configuration model against buy-and-hold, baseline,
%   and exposure outputs for each ticker.
%
% Current selected configuration:
%   SPY  -> Baseline 0/1 strategy, r_meas = 5e-4
%   QQQ  -> Softened exposure strategy, r_meas = 1e-3
%   SPYG -> Softened exposure strategy, r_meas = 1e-3
%
% Important:
%   This script does NOT replace the baseline or exposure outputs.
%   It runs each ticker with its selected r_meas and reports all branches:
%       1. Buy-and-hold
%       2. Baseline 0/1 Kalman strategy
%       3. Partial-exposure Kalman strategy
%       4. Selected strategy

clear; clc; close all;

%% ---------------- Path Setup ----------------
% Assumes this script is inside:
%   Selected Strategy mode/
%
% and the data folder is one level above:
%   ../data/
scriptDir = string(fileparts(mfilename('fullpath')));
projectRoot = string(fileparts(scriptDir));

dataDir = fullfile(projectRoot, "data");

%% ---------------- Model Configuration Table ----------------
modelConfig = table( ...
    ["SPY";  "QQQ";      "SPYG"], ...
    ["Baseline"; "Exposure"; "Exposure"], ...
    [5e-4; 1e-3; 1e-3], ...
    [1e-7; 1e-7; 1e-7], ...
    [5; 5; 5], ...
    [8; 8; 8], ...
    'VariableNames', ["Ticker", "SelectedStrategy", "r_meas", "q_jerk", "BuyConfirmDays", "SellConfirmDays"]);

numTickers = height(modelConfig);

summaryRows = table();

%% ---------------- Shared Non-Model Settings ----------------
transactionCost = 0.001;

makePlots = true;
showStatePlots = false;
printSummary = false;

runPartialExposure = true;

%% ---------------- Run Batch Tests ----------------
for i = 1:numTickers

    ticker = modelConfig.Ticker(i);
    filename = fullfile(dataDir, ticker + ".csv");

    fprintf("Running selected configuration for %s...\n", ticker);

    %% ---------------- Ticker-Specific Parameters ----------------
    params = struct();

    params.q_jerk = modelConfig.q_jerk(i);
    params.r_meas = modelConfig.r_meas(i);

    params.buyConfirmDays = modelConfig.BuyConfirmDays(i);
    params.sellConfirmDays = modelConfig.SellConfirmDays(i);

    params.transactionCost = transactionCost;

    params.makePlots = makePlots;
    params.showStatePlots = showStatePlots;
    params.printSummary = printSummary;

    params.runPartialExposure = runPartialExposure;

    [results, summary] = runKalmanTrendModel_partialExposure(filename, params); %#ok<ASGLU>

    %% ---------------- Selected Strategy Metrics ----------------
    selectedStrategy = modelConfig.SelectedStrategy(i);

    if selectedStrategy == "Exposure"

        selectedReturnPct = 100*summary.exposureTotalReturn;
        selectedMaxDrawdownPct = 100*summary.exposureMaxDrawdown;
        selectedSharpe = summary.exposureSharpeApprox;
        selectedBuyCount = summary.exposureBuyCount;
        selectedSellCount = summary.exposureSellCount;
        selectedTradeCount = summary.exposureTradeCount;
        selectedTimeInMarketPct = 100*summary.exposureTimeInMarket;
        selectedAverageExposurePct = 100*summary.averageExposure;
        selectedExcessReturnPct = 100*summary.exposureExcessReturn;
        selectedDrawdownImprovementPct = 100*summary.exposureDrawdownImprovement;
        selectedSharpeImprovement = summary.exposureSharpeImprovement;

    elseif selectedStrategy == "Baseline"

        selectedReturnPct = 100*summary.baselineTotalReturn;
        selectedMaxDrawdownPct = 100*summary.baselineMaxDrawdown;
        selectedSharpe = summary.baselineSharpeApprox;
        selectedBuyCount = summary.baselineBuyCount;
        selectedSellCount = summary.baselineSellCount;
        selectedTradeCount = summary.baselineTradeCount;
        selectedTimeInMarketPct = 100*summary.baselineTimeInMarket;
        selectedAverageExposurePct = 100*summary.baselineTimeInMarket;
        selectedExcessReturnPct = 100*summary.baselineExcessReturn;
        selectedDrawdownImprovementPct = 100*summary.baselineDrawdownImprovement;
        selectedSharpeImprovement = summary.baselineSharpeImprovement;

    else
        error("Unknown SelectedStrategy for %s. Use 'Baseline' or 'Exposure'.", ticker);
    end

    %% ---------------- Output Row ----------------
    newRow = table( ...
        ticker, ...
        selectedStrategy, ...
        summary.startDate, ...
        summary.endDate, ...
        summary.q_jerk, ...
        summary.r_meas, ...
        summary.buyConfirmDays, ...
        summary.sellConfirmDays, ...
        100*summary.buyHoldTotalReturn, ...
        100*summary.baselineTotalReturn, ...
        100*summary.exposureTotalReturn, ...
        selectedReturnPct, ...
        100*summary.buyHoldMaxDrawdown, ...
        100*summary.baselineMaxDrawdown, ...
        100*summary.exposureMaxDrawdown, ...
        selectedMaxDrawdownPct, ...
        summary.buyHoldSharpeApprox, ...
        summary.baselineSharpeApprox, ...
        summary.exposureSharpeApprox, ...
        selectedSharpe, ...
        summary.buyHoldBuyCount, ...
        summary.baselineBuyCount, ...
        summary.exposureBuyCount, ...
        selectedBuyCount, ...
        summary.buyHoldSellCount, ...
        summary.baselineSellCount, ...
        summary.exposureSellCount, ...
        selectedSellCount, ...
        summary.buyHoldTradeCount, ...
        summary.baselineTradeCount, ...
        summary.exposureTradeCount, ...
        selectedTradeCount, ...
        100*summary.buyHoldTimeInMarket, ...
        100*summary.baselineTimeInMarket, ...
        100*summary.exposureTimeInMarket, ...
        selectedTimeInMarketPct, ...
        100*summary.averageExposure, ...
        selectedAverageExposurePct, ...
        summary.exposureTurnoverTotal, ...
        summary.exposureTargetAdjustmentCount, ...
        summary.exposureHysteresisDelayCount, ...
        summary.maxSellPressure, ...
        summary.avgSellPressureWhileLong, ...
        100*summary.buyHoldExcessReturn, ...
        100*summary.baselineExcessReturn, ...
        100*summary.exposureExcessReturn, ...
        selectedExcessReturnPct, ...
        100*summary.buyHoldDrawdownImprovement, ...
        100*summary.baselineDrawdownImprovement, ...
        100*summary.exposureDrawdownImprovement, ...
        selectedDrawdownImprovementPct, ...
        summary.buyHoldSharpeImprovement, ...
        summary.baselineSharpeImprovement, ...
        summary.exposureSharpeImprovement, ...
        selectedSharpeImprovement, ...
        'VariableNames', [ ...
        "Ticker", ...
        "SelectedStrategy", ...
        "StartDate", ...
        "EndDate", ...
        "q_jerk", ...
        "r_meas", ...
        "BuyConfirmDays", ...
        "SellConfirmDays", ...
        "BuyHoldReturnPct", ...
        "BaselineReturnPct", ...
        "ExposureReturnPct", ...
        "SelectedReturnPct", ...
        "BuyHoldMaxDrawdownPct", ...
        "BaselineMaxDrawdownPct", ...
        "ExposureMaxDrawdownPct", ...
        "SelectedMaxDrawdownPct", ...
        "BuyHoldSharpe", ...
        "BaselineSharpe", ...
        "ExposureSharpe", ...
        "SelectedSharpe", ...
        "BuyHoldBuyCount", ...
        "BaselineBuyCount", ...
        "ExposureBuyCount", ...
        "SelectedBuyCount", ...
        "BuyHoldSellCount", ...
        "BaselineSellCount", ...
        "ExposureSellCount", ...
        "SelectedSellCount", ...
        "BuyHoldTradeCount", ...
        "BaselineTradeCount", ...
        "ExposureTradeCount", ...
        "SelectedTradeCount", ...
        "BuyHoldTimeInMarketPct", ...
        "BaselineTimeInMarketPct", ...
        "ExposureTimeInMarketPct", ...
        "SelectedTimeInMarketPct", ...
        "ExposureAveragePct", ...
        "SelectedAverageExposurePct", ...
        "ExposureTurnoverTotal", ...
        "ExposureTargetAdjustmentCount", ...
        "ExposureHysteresisDelayCount", ...
        "MaxSellPressure", ...
        "AvgSellPressureWhileLong", ...
        "BuyHoldExcessReturnPct", ...
        "BaselineExcessReturnPct", ...
        "ExposureExcessReturnPct", ...
        "SelectedExcessReturnPct", ...
        "BuyHoldDrawdownImprovementPct", ...
        "BaselineDrawdownImprovementPct", ...
        "ExposureDrawdownImprovementPct", ...
        "SelectedDrawdownImprovementPct", ...
        "BuyHoldSharpeImprovement", ...
        "BaselineSharpeImprovement", ...
        "ExposureSharpeImprovement", ...
        "SelectedSharpeImprovement"]);

    summaryRows = [summaryRows; newRow];

end

%% ---------------- Display Summary ----------------
disp(summaryRows);

%% ---------------- Save Results ----------------
% Save results inside:
%   Selected Strategy mode/results/batchruns/
resultsDir = fullfile(scriptDir, "results");
batchRunsDir = fullfile(resultsDir, "batchruns");

if ~isfolder(resultsDir)
    mkdir(resultsDir);
end

if ~isfolder(batchRunsDir)
    mkdir(batchRunsDir);
end

outFile = fullfile(batchRunsDir, "batch_selected_config_strategy.xlsx");
writetable(summaryRows, outFile);

fprintf("\nSelected-configuration batch summary saved to: %s\n", outFile);
